### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by dotxnc** [TheLumaio/Zero-G-Shooter#3]
### Bugs
- [x] Random crash when client connects.
- [ ] Shadows don't work sometimes.
### TODO
- [ ] Remove player nodes when client disconnects.
- [ ] Map collisions.
